#!/usr/bin/env python3
"""
nx_schema_review.py - Interactive Schema Review for Nexus

Reviews a draft schema generated by nx_schema_gen.py. Shows confidence
scores, highlights low-confidence fields, and allows field-by-field
approve/reject/edit before saving to schemas/.

Usage:
    python3 nx_schema_review.py draft_schema.json [options]

Options:
    --output DIR     Output directory for approved schemas (default: schemas/)
    --auto-approve   Auto-approve fields with confidence >= threshold
    --threshold N    Auto-approve threshold (default: 0.8)
"""

import json
import sys
import os
import argparse
import re
from pathlib import Path


def color(text: str, code: str) -> str:
    """ANSI color wrapper (respects NO_COLOR env)."""
    if os.environ.get("NO_COLOR") or not sys.stdout.isatty():
        return text
    codes = {"red": "31", "green": "32", "yellow": "33", "blue": "34",
             "bold": "1", "dim": "2", "reset": "0"}
    return f"\033[{codes.get(code, '0')}m{text}\033[0m"


def print_header(draft: dict):
    """Print draft schema summary."""
    print(f"\n{'='*60}")
    print(color("  Nexus Schema Review", "bold"))
    print(f"{'='*60}\n")

    print(f"  Generated by: {draft.get('generated_by', 'unknown')}")
    print(f"  Generated at: {draft.get('generated_at', 'unknown')}")
    print(f"  Source SHA:    {draft.get('source_sha256', 'unknown')[:16]}...")
    print(f"  Ensemble size: {draft.get('ensemble_size', 0)}")

    confidence = draft.get("confidence", {})
    overall = confidence.get("overall", 0)
    overall_color = "green" if overall >= 0.8 else "yellow" if overall >= 0.6 else "red"
    print(f"  Overall confidence: {color(f'{overall:.0%}', overall_color)}")
    print()


def print_schema_summary(schema: dict):
    """Print schema structure overview."""
    print(color("Schema Structure:", "bold"))
    print(f"  Version:     {schema.get('version', 'unset')}")
    print(f"  Output type: {schema.get('output_type', 'unset')}")
    print(f"  Schema ver:  nx_schema {schema.get('nx_schema', 1)}")

    columns = schema.get("columns", [])
    print(f"  Columns:     {len(columns)}")

    multi = schema.get("multi_transforms", [])
    if multi:
        print(f"  Multi-transforms: {len(multi)}")

    derived = schema.get("derived", [])
    if derived:
        print(f"  Derived fields:   {len(derived)}")

    validate = schema.get("validate", [])
    if validate:
        print(f"  Validation rules: {len(validate)}")

    row_id = schema.get("row_id")
    if row_id:
        print(f"  Row ID template:  {row_id.get('template', 'none')}")

    print()


def review_fields(schema: dict, confidence: dict, auto_approve: bool,
                  threshold: float) -> dict:
    """Interactive field-by-field review. Returns modified schema."""
    fields = confidence.get("fields", {})
    columns = schema.get("columns", [])

    print(color("Column Mappings:", "bold"))
    print(f"  {'#':>3} {'Source':>6} {'Target':<20} {'Type':<8} {'Req':>3} {'Conf':>6} {'Status':<10}")
    print(f"  {'─'*3} {'─'*6} {'─'*20} {'─'*8} {'─'*3} {'─'*6} {'─'*10}")

    approved = []
    for i, col in enumerate(columns):
        target = col.get("target", "?")
        source = col.get("source", -1)
        ctype = col.get("type", "string")
        required = "yes" if col.get("required") else "no"

        field_info = fields.get(target, {})
        conf = field_info.get("confidence", 0)
        votes = field_info.get("votes", "?/?")

        conf_color = "green" if conf >= 0.8 else "yellow" if conf >= 0.6 else "red"

        if auto_approve and conf >= threshold:
            status = color("auto-ok", "green")
            approved.append(col)
            print(f"  {i:>3} {source:>6} {target:<20} {ctype:<8} {required:>3} "
                  f"{color(f'{conf:.0%}', conf_color):>15} {status}")
        else:
            status = color("review", "yellow")
            print(f"  {i:>3} {source:>6} {target:<20} {ctype:<8} {required:>3} "
                  f"{color(f'{conf:.0%}', conf_color):>15} {status}")

            # Interactive review
            while True:
                choice = input(f"    [{color('a', 'green')}]pprove / "
                               f"[{color('r', 'red')}]eject / "
                               f"[{color('e', 'yellow')}]dit / "
                               f"[{color('s', 'blue')}]kip: ").strip().lower()

                if choice in ("a", "approve", ""):
                    approved.append(col)
                    print(f"    {color('Approved', 'green')}")
                    break
                elif choice in ("r", "reject"):
                    print(f"    {color('Rejected', 'red')}")
                    break
                elif choice in ("e", "edit"):
                    # Edit target name
                    new_target = input(f"    New target name [{target}]: ").strip()
                    if new_target:
                        col["target"] = new_target

                    # Edit type
                    new_type = input(f"    New type [{ctype}]: ").strip()
                    if new_type in ("string", "int", "double", "bool"):
                        col["type"] = new_type

                    # Edit required
                    new_req = input(f"    Required? [{required}]: ").strip().lower()
                    if new_req in ("yes", "true", "y"):
                        col["required"] = True
                    elif new_req in ("no", "false", "n"):
                        col.pop("required", None)

                    approved.append(col)
                    print(f"    {color('Edited and approved', 'yellow')}")
                    break
                elif choice in ("s", "skip"):
                    approved.append(col)
                    print(f"    {color('Skipped (kept as-is)', 'dim')}")
                    break

    schema["columns"] = approved
    print(f"\n  {len(approved)}/{len(columns)} columns approved\n")
    return schema


def review_metadata(schema: dict) -> dict:
    """Review and edit schema metadata."""
    print(color("Schema Metadata:", "bold"))

    # Version
    version = schema.get("version", "")
    print(f"  Version: {version}")
    new_version = input(f"  New version [{version}]: ").strip()
    if new_version:
        schema["version"] = new_version

    # Output type
    output_type = schema.get("output_type", "")
    print(f"  Output type: {output_type}")
    new_type = input(f"  New output type [{output_type}]: ").strip()
    if new_type:
        schema["output_type"] = new_type

    print()
    return schema


def bump_version(version: str) -> str:
    """Increment version number: foo-v1 → foo-v2."""
    match = re.match(r"^(.+)-v(\d+)$", version)
    if match:
        base = match.group(1)
        num = int(match.group(2)) + 1
        return f"{base}-v{num}"
    return version + "-v1"


def save_schema(schema: dict, output_dir: str):
    """Save approved schema to output directory."""
    output_path = Path(output_dir)
    output_path.mkdir(parents=True, exist_ok=True)

    version = schema.get("version", "unknown")
    filename = f"{version}.json"
    filepath = output_path / filename

    # Check for existing file
    if filepath.exists():
        print(f"\n  {color('Warning:', 'yellow')} {filepath} already exists.")
        choice = input(f"  [{color('o', 'yellow')}]verwrite / "
                       f"[{color('b', 'green')}]ump version / "
                       f"[{color('c', 'red')}]ancel: ").strip().lower()

        if choice in ("b", "bump"):
            new_version = bump_version(version)
            schema["version"] = new_version
            filename = f"{new_version}.json"
            filepath = output_path / filename
            print(f"  Bumped to {new_version}")
        elif choice in ("c", "cancel"):
            print("  Cancelled.")
            return
        # else overwrite

    with open(filepath, "w") as f:
        json.dump(schema, f, indent=2, ensure_ascii=False)
        f.write("\n")

    print(f"\n  {color('Saved:', 'green')} {filepath}")


def main():
    parser = argparse.ArgumentParser(description="Interactive schema review for Nexus")
    parser.add_argument("input", help="Path to draft schema JSON (from nx_schema_gen.py)")
    parser.add_argument("--output", "-o", default="schemas/",
                        help="Output directory for approved schemas")
    parser.add_argument("--auto-approve", action="store_true",
                        help="Auto-approve fields with high confidence")
    parser.add_argument("--threshold", type=float, default=0.8,
                        help="Auto-approve threshold (default: 0.8)")

    args = parser.parse_args()

    # Load draft
    with open(args.input) as f:
        draft = json.load(f)

    if "schema" not in draft:
        print("Error: Input file does not contain a 'schema' key", file=sys.stderr)
        print("Expected output from nx_schema_gen.py", file=sys.stderr)
        sys.exit(1)

    schema = draft["schema"]
    confidence = draft.get("confidence", {})

    # Display
    print_header(draft)
    print_schema_summary(schema)

    # Review metadata
    schema = review_metadata(schema)

    # Review fields
    schema = review_fields(schema, confidence, args.auto_approve, args.threshold)

    # Review multi-transforms
    multi = schema.get("multi_transforms", [])
    if multi:
        print(color("Multi-Transforms:", "bold"))
        for i, mt in enumerate(multi):
            print(f"  {i}: type={mt.get('type')}, "
                  f"source={mt.get('source', mt.get('sources', '?'))}")
        choice = input(f"\n  Keep all multi-transforms? [{color('y', 'green')}/n]: ").strip().lower()
        if choice in ("n", "no"):
            schema["multi_transforms"] = []
            print(f"  {color('Removed all multi-transforms', 'red')}")
        print()

    # Review validation
    validate = schema.get("validate", [])
    if validate:
        print(color("Validation Rules:", "bold"))
        for i, rule in enumerate(validate):
            print(f"  {i}: type={rule.get('type')}, severity={rule.get('severity', 'error')}")
        choice = input(f"\n  Keep all validation rules? [{color('y', 'green')}/n]: ").strip().lower()
        if choice in ("n", "no"):
            schema["validate"] = []
            print(f"  {color('Removed all validation rules', 'red')}")
        print()

    # Final confirmation
    print(color("Final Schema Preview:", "bold"))
    print(json.dumps(schema, indent=2, ensure_ascii=False))

    print()
    choice = input(f"  Save this schema? [{color('y', 'green')}/n]: ").strip().lower()
    if choice not in ("n", "no"):
        save_schema(schema, args.output)
    else:
        print("  Not saved.")


if __name__ == "__main__":
    main()
