import { useState } from 'react';
import { Sparkles, Loader2, RefreshCw } from 'lucide-react';
import { api } from '@/lib/api';
import { useI18n, useT } from '@/i18n';

/* Sage (LLM) narration of a plan or a comparison, in the current UI language.
 * The text is generated by the backend from the plan's own figures (the model
 * is told to use only those). Degrades gracefully: if Sage is unreachable the
 * request fails and we show an "unavailable" note. On demand only. */
export function NarrationPanel({ planId, compare }: { planId?: string; compare?: { base: string; revised: string } }) {
  const { lang } = useI18n();
  const t = useT();
  const [text, setText] = useState<string | null>(null);
  const [state, setState] = useState<'idle' | 'loading' | 'error'>('idle');

  async function run() {
    setState('loading'); setText(null);
    try {
      const r = compare
        ? await api.narrateCompare(compare.base, compare.revised, lang)
        : await api.narratePlan(planId!, lang);
      setText(r.text); setState('idle');
    } catch {
      setState('error');
    }
  }

  return (
    <div className="rounded-md border border-divider bg-muted/30 p-2.5">
      <div className="mb-1.5 flex items-center justify-between gap-2">
        <span className="flex items-center gap-1.5 text-xs font-semibold uppercase tracking-wide text-muted-foreground">
          <Sparkles className="h-3.5 w-3.5" /> {t('narr.title')}
        </span>
        <button type="button" onClick={() => void run()} disabled={state === 'loading'}
          className="inline-flex items-center gap-1 rounded px-1.5 py-0.5 text-[11px] font-medium text-primary hover:bg-primary/10 disabled:opacity-50">
          {state === 'loading'
            ? <><Loader2 className="h-3 w-3 animate-spin" /> {t('narr.generating')}</>
            : text ? <><RefreshCw className="h-3 w-3" /> {t('narr.regenerate')}</>
                   : <><Sparkles className="h-3 w-3" /> {t('narr.generate')}</>}
        </button>
      </div>
      {state === 'error' && <p className="text-[11px] text-warning">{t('narr.unavailable')}</p>}
      {text && <p className="whitespace-pre-line text-xs leading-relaxed text-foreground/90">{text}</p>}
      <p className="mt-1 text-[10px] text-muted-foreground">{t('narr.caption')}</p>
    </div>
  );
}
