/*
 * Carta API Handler - Transport-agnostic request handling
 *
 * This module provides request handling logic that can be used by:
 * - Mongoose HTTP server (production)
 * - WASM exports (browser demo)
 * - Direct C API calls (testing)
 *
 * The API handler is initialized with PBF data and handles path-based
 * routing internally. All responses are returned as allocated buffers
 * that the caller must free.
 */

#ifndef CARTA_CT_API_H
#define CARTA_CT_API_H

#include <stddef.h>
#include <stdint.h>
#include "ct_types.h"  /* For CTPBFContext, CTLODConfig */

#ifdef __cplusplus
extern "C" {
#endif

/* ============================================================================
 * API Endpoint Documentation
 *
 * These annotations are parsed by scripts/build-api-docs.py to generate site/api.html
 * ============================================================================ */

/*@api
 * GET /tiles/{z}/{x}/{y}.png
 * Raster tile (PNG)
 *
 * @path z:int Zoom level (0-18)
 * @path x:int Tile X coordinate
 * @path y:int Tile Y coordinate
 *
 * @returns image/png PNG image (512x512 by default). Content-Type: image/png
 * @error 400 Invalid coordinates
 * @error 404 Outside map bounds
 *
 * @example curl http://localhost:8081/tiles/14/8529/5974.png -o tile.png
 * @example_comment Get tile at zoom 14, Monaco area
 *
 * @demo image
 * @demo_title Generate a tile using Carta WASM with embedded Monaco data. No server required.
 * @demo_input z:number:14:0:18
 * @demo_input x:number:8529
 * @demo_input y:number:5974
 */

/*@api
 * GET /tiles/{z}/{x}/{y}.mvt
 * Vector tile (MVT/Protobuf)
 *
 * @path z:int Zoom level (0-18)
 * @path x:int Tile X coordinate
 * @path y:int Tile Y coordinate
 *
 * @returns application/x-protobuf Mapbox Vector Tile format. Use with MapLibre GL JS or similar vector tile renderers.
 * @error 400 Invalid coordinates
 * @error 404 Outside map bounds
 */

/*@api
 * GET /tiles/{z}/{x}/{y}.txt
 * ASCII art tile
 *
 * @path z:int Zoom level
 * @path x:int Tile X coordinate
 * @path y:int Tile Y coordinate
 * @query width:int:80 Output width in characters (20-400, default: 80)
 * @query height:int:0 Output height (0=auto from aspect ratio)
 * @query charset:string:extended simple, extended (default), blocks, braille
 * @query invert:bool:0 1 for light background terminals
 * @query color:bool:0 1 for ANSI 256-color output
 *
 * @returns text/plain ASCII art representation of the tile
 *
 * @example curl "http://localhost:8081/tiles/14/9058/5729.txt?width=120&charset=blocks"
 * @example_comment ASCII map in terminal
 */

/*@api
 * GET /tiles.json
 * TileJSON metadata
 *
 * @returns application/json TileJSON 3.0.0 specification
 * @response_json
 * {
 *   "tilejson": "3.0.0",
 *   "name": "OTTO Carta",
 *   "description": "Map tiles generated by Carta",
 *   "version": "1.0.0",
 *   "attribution": "OpenStreetMap contributors",
 *   "scheme": "xyz",
 *   "tiles": ["http://localhost:8081/tiles/{z}/{x}/{y}.png"],
 *   "vector_tiles": ["http://localhost:8081/tiles/{z}/{x}/{y}.mvt"],
 *   "minzoom": 0,
 *   "maxzoom": 18,
 *   "bounds": [7.41, 43.72, 7.44, 43.75],
 *   "center": [7.42, 43.73, 10]
 * }
 *
 * @demo json
 * @demo_title Fetch TileJSON metadata from embedded Monaco data.
 */

/*@wasm
 * @export carta_api_init
 * @export carta_api_free
 * @export carta_api_ready
 * @export carta_api_handle
 * @export carta_response_status
 * @export carta_response_content_type
 * @export carta_response_body
 * @export carta_response_body_len
 * @export carta_api_pbf_size
 * @export carta_api_version
 * @export malloc
 * @export free
 */

/* ============================================================================
 * API Context
 * ============================================================================ */

/*
 * Opaque API context - holds all state needed for request handling.
 * Thread-safe for concurrent requests once initialized.
 */
typedef struct CTAPIContext CTAPIContext;

/*
 * API configuration options.
 */
typedef struct {
    int min_zoom;           /* Minimum zoom level (default: 0) */
    int max_zoom;           /* Maximum zoom level (default: 18) */
    int tile_size;          /* PNG tile size (default: 512) */
    int enable_lod;         /* Enable LOD filtering (default: 1) */
    const char *name;       /* Server name for TileJSON (optional) */
} CTAPIConfig;

/*
 * Initialize default API configuration.
 */
void ct_api_config_init(CTAPIConfig *config);

/*
 * Create API context from PBF data in memory.
 *
 * This is the primary initialization path for both server and WASM.
 * The data is copied internally - caller can free pbf_data after this call.
 *
 * Returns NULL on failure.
 */
CTAPIContext *ct_api_create(const uint8_t *pbf_data, size_t pbf_len,
                            const CTAPIConfig *config);

/*
 * Create API context from an existing PBF context.
 *
 * This allows sharing a PBF context between the API handler and other
 * code (e.g., the mongoose server's caching layer).
 *
 * The PBF context is NOT owned by the API context - caller must keep
 * it alive and free it separately.
 *
 * Returns NULL on failure.
 */
CTAPIContext *ct_api_create_from_pbf(CTPBFContext *pbf_ctx,
                                     const CTAPIConfig *config);

/*
 * Free API context.
 *
 * If created with ct_api_create(), frees the internal PBF context.
 * If created with ct_api_create_from_pbf(), does NOT free the PBF context.
 */
void ct_api_free(CTAPIContext *ctx);

/*
 * Get the underlying PBF context (for advanced use).
 */
CTPBFContext *ct_api_get_pbf(CTAPIContext *ctx);

/*
 * Set LOD configuration.
 * Use this to apply custom LOD settings after context creation.
 */
void ct_api_set_lod(CTAPIContext *ctx, const CTLODConfig *lod);

/*
 * Set render options.
 * Use this to apply custom render settings after context creation.
 */
void ct_api_set_render_opts(CTAPIContext *ctx, const CTRenderOptions *opts);

/*
 * Disable LOD filtering entirely.
 */
void ct_api_disable_lod(CTAPIContext *ctx);

/* ============================================================================
 * Request/Response
 * ============================================================================ */

/*
 * API request structure.
 *
 * The path should be the URI path (e.g., "/tiles/14/8529/5974.png").
 * The query string is optional and should NOT include the leading '?'.
 */
typedef struct {
    const char *path;       /* URI path (required) */
    const char *query;      /* Query string without '?' (optional, NULL ok) */
    const char *host;       /* Host header for TileJSON URLs (optional) */
} CTAPIRequest;

/*
 * API response structure.
 *
 * The body is heap-allocated and must be freed by the caller using
 * ct_api_response_free() or free().
 */
typedef struct {
    int status_code;        /* HTTP status code (200, 400, 404, 500, etc.) */
    const char *content_type; /* MIME type (static string, do not free) */
    uint8_t *body;          /* Response body (caller must free) */
    size_t body_len;        /* Response body length in bytes */
} CTAPIResponse;

/*
 * Handle an API request.
 *
 * Routes the request based on path and generates the appropriate response.
 * The response body is heap-allocated - caller must free with
 * ct_api_response_free().
 *
 * Supported paths:
 *   /tiles/{z}/{x}/{y}.png  - PNG tile
 *   /tiles/{z}/{x}/{y}.mvt  - MVT tile
 *   /tiles.json             - TileJSON metadata
 *   /api/v1/health          - Health check
 *   /api/v1/stats           - PBF statistics
 *
 * Returns 0 on success (response filled in), -1 on internal error.
 */
int ct_api_handle(CTAPIContext *ctx,
                  const CTAPIRequest *req,
                  CTAPIResponse *resp);

/*
 * Free response body.
 *
 * Safe to call with NULL response or NULL body.
 */
void ct_api_response_free(CTAPIResponse *resp);

/* ============================================================================
 * Individual Handlers (for advanced use)
 * ============================================================================ */

/*
 * Generate a PNG tile.
 *
 * Returns allocated PNG data, or NULL on failure.
 * Caller must free the returned buffer.
 */
uint8_t *ct_api_generate_png(CTAPIContext *ctx,
                             int z, int x, int y,
                             size_t *out_len);

/*
 * Generate an MVT tile.
 *
 * Returns allocated MVT data, or NULL on failure (empty tiles return
 * a minimal valid MVT).
 * Caller must free the returned buffer.
 */
uint8_t *ct_api_generate_mvt(CTAPIContext *ctx,
                             int z, int x, int y,
                             size_t *out_len);

/*
 * Generate TileJSON metadata.
 *
 * The host parameter is used to build tile URLs (e.g., "localhost:8081").
 * If NULL, uses "localhost".
 *
 * Returns allocated JSON string, or NULL on failure.
 * Caller must free the returned buffer.
 */
char *ct_api_generate_tilejson(CTAPIContext *ctx,
                               const char *host,
                               size_t *out_len);

/*
 * Generate health check response.
 *
 * Returns allocated JSON string.
 * Caller must free the returned buffer.
 */
char *ct_api_generate_health(CTAPIContext *ctx, size_t *out_len);

/*
 * Generate stats response.
 *
 * Returns allocated JSON string.
 * Caller must free the returned buffer.
 */
char *ct_api_generate_stats(CTAPIContext *ctx, size_t *out_len);

/*
 * Generate an ASCII art tile.
 *
 * Renders the tile to pixels, then converts to ASCII art.
 * Query parameters control output: width, height, charset, invert, color.
 *
 * Returns allocated ASCII string, or NULL on failure.
 * Caller must free the returned buffer.
 */
char *ct_api_generate_ascii(CTAPIContext *ctx,
                            int z, int x, int y,
                            const char *query,
                            size_t *out_len);

#ifdef __cplusplus
}
#endif

#endif /* CARTA_CT_API_H */
